import React, { useState } from 'react';
import { X, Copy, Check } from 'lucide-react';
import { ExtractedSignaturePage } from '../types';

interface InstructionsModalProps {
  isOpen: boolean;
  onClose: () => void;
  pages: ExtractedSignaturePage[];
}

const InstructionsModal: React.FC<InstructionsModalProps> = ({ isOpen, onClose, pages }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Group by Party
  const parties: string[] = (Array.from(new Set(pages.map(p => p.partyName))) as string[]).sort();
  const groupedPages: Record<string, ExtractedSignaturePage[]> = {};
  
  parties.forEach(party => {
    groupedPages[party] = pages.filter(p => p.partyName === party && p.copies > 0);
  });

  const handleCopy = () => {
    let text = `SIGNING INSTRUCTIONS\nGenerated by Signature Packet IDE\n\n`;
    
    Object.entries(groupedPages).forEach(([party, partyPages]) => {
      if (partyPages.length === 0) return;
      text += `${party.toUpperCase()}\n`;
      text += '-'.repeat(party.length) + '\n';
      partyPages.forEach(p => {
        text += `• ${p.documentName}\n`;
        const sigText = p.signatoryName ? ` by ${p.signatoryName}` : '';
        text += `  Sign as: ${p.capacity}${sigText} (${p.copies} ${p.copies === 1 ? 'copy' : 'copies'})\n`;
      });
      text += '\n';
    });

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-xl shadow-2xl flex flex-col animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="bg-slate-50 border-b border-slate-200 px-6 py-4 flex items-center justify-between rounded-t-xl">
          <h3 className="font-bold text-lg text-slate-800">Signing Instructions</h3>
          <div className="flex items-center gap-2">
            <button 
                onClick={handleCopy}
                className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-md transition-colors"
            >
                {copied ? <Check size={16} /> : <Copy size={16} />}
                {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
            <button 
                onClick={onClose}
                className="p-2 hover:bg-slate-200 rounded-full text-slate-400 hover:text-slate-800 transition-colors"
            >
                <X size={20} />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
            <div className="space-y-8">
                {parties.map(party => {
                    const partyPages = groupedPages[party];
                    if (partyPages.length === 0) return null;

                    return (
                        <div key={party} className="border border-slate-200 rounded-lg overflow-hidden">
                            <div className="bg-slate-50 px-4 py-2 border-b border-slate-200 font-semibold text-slate-700">
                                {party}
                            </div>
                            <table className="w-full text-sm text-left">
                                <thead className="text-xs text-slate-500 uppercase bg-slate-50/50">
                                    <tr>
                                        <th className="px-4 py-2 font-medium">Document</th>
                                        <th className="px-4 py-2 font-medium">Capacity</th>
                                        <th className="px-4 py-2 font-medium">Signatory</th>
                                        <th className="px-4 py-2 font-medium w-24 text-center">Copies</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-100">
                                    {partyPages.map(p => (
                                        <tr key={p.id} className="hover:bg-slate-50">
                                            <td className="px-4 py-2.5 text-slate-700">{p.documentName}</td>
                                            <td className="px-4 py-2.5 text-slate-600 italic">{p.capacity}</td>
                                            <td className="px-4 py-2.5 text-slate-600">{p.signatoryName || '-'}</td>
                                            <td className="px-4 py-2.5 text-center font-semibold text-slate-700">{p.copies}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    );
                })}
            </div>
        </div>
      </div>
    </div>
  );
};

export default InstructionsModal;